name: actions_python_coveralls
description: A Github action for running pytest with coverage and pushing results to coveralls
branding:
  icon: 'check-circle'
  color: 'green'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - uses: davidslusser/actions/.github/workflows/covralls.yaml@main
