name: actions_python_coveralls
description: A Github action for running pytest with coverage and pushing results to coveralls
branding:
  icon: 'check-circle'
  color: 'green'
inputs:
  coveralls_repo_token:
    description: "coveralls repo token"
    required: true
    type: string
  options:
    required: false
    type: string
    default: "--cov"  
  pip_install_command: 
    description: "command used to install python dependancies"
    required: false
    type: string
    default: "pip install coveralls pytest pytest-cov"
  python_version:
    description: "version of python to run action with"
    required: false
    type: string
    default: "3.x"
  src:
    required: false
    type: string
    default: "."
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: "Setup Python ${{ inputs.python_version }}"
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}
    
    - name: "Show Python Version"
      run: python --version
      shell: bash

    - name: "Install Python Dependencies"
      run: |
        python -m pip install --upgrade pip
        ${{ inputs.pip_install_command }}
      shell: bash
       
    - name: "Run Tests"
      run: "coverage run --source=${{ inputs.src }} -m pytest ${{ inputs.options }}"
      shell: bash
    
    - name: "Push To Coveralls"
      run: "coveralls"
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
        COVERALLS_REPO_TOKEN: ${{ inputs.coveralls_repo_token }}  
