name: actions_python_coveralls
description: A Github action for running pytest with coverage and pushing results to coveralls
branding:
  icon: 'check-circle'
  color: 'green'
runs:
  using: "composite"
  steps:
    - uses: davidslusser/actions/.github/workflows/covralls.yaml@main
