name: actions_python_coveralls
description: A Github action for running pytest with coverage and pushing results to coveralls
branding:
  icon: 'check-circle'
  color: 'green'
inputs:
  src:
    description: source directory used for code coverage
    required: false
  options:
    description: optional flags/parameters used in pytest command
    required: false
  pip_install_command:
    description: command used to install dependancies
    required: false
  python_version:
    description: version of python to use
    required: false
runs:
  using: "composite"
  steps:
    - name: Local Action Call
      run: |
        echo "Hello World"
      shell: bash

